apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: output
  params:
    - name: app-name
      type: string
      description: Name of the app to deploy
    - name: build-image
      type: string
      description: Image built to deploy
  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: output

    - name: git-clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: https://github.com/Dewranga-Bandara/ci-cd-final-project.git
      workspaces:
        - name: output
          workspace: output

    - name: flake8-lint
      taskRef:
        name: flake8
      workspaces:
        - name: source
          workspace: output

    - name: nose-test
      taskRef:
        name: nose
      workspaces:
        - name: source
          workspace: output

    - name: buildah
      taskRef:
        name: buildah
      workspaces:
        - name: source
          workspace: output

    - name: oc-deploy
      taskRef:
        name: openshift-client
      params:
        - name: SCRIPT
          value: |
            oc create deployment $(params.app-name) --image=$(params.build-image) --dry-run=client -o yaml | oc apply -f -
      workspaces:
        - name: source
          workspace: output
